In [53]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sqlite3
import re

In [54]:
df_a_inicio = pd.read_csv('/workspaces/moneyball-brasileirao/data/valores_a_inicio.csv', sep = ',')
df_b_inicio = pd.read_csv('/workspaces/moneyball-brasileirao/data/valores_b_inicio.csv', sep = ',')
df_a_fim = pd.read_csv('/workspaces/moneyball-brasileirao/data/valores_c_fim.csv', sep = ',')
df_b_fim = pd.read_csv('/workspaces/moneyball-brasileirao/data/valores_d_fim.csv', sep = ',')
df_class = pd.read_csv('/workspaces/moneyball-brasileirao/data/classClubes.csv', sep = ',')
df_geral = pd.read_csv('/workspaces/moneyball-brasileirao/data/valores_geral.csv', sep = ',')

In [55]:
display(df_a_inicio,df_b_inicio,df_a_fim,df_b_fim, df_class, df_geral)

,#,wappen,Clube,Clube.1,Pertence à liga01/01/2025,Valor01/01/2025,Jogadores no plantel 01/01/2025,Valor atual,Jogadores no plantel,Diferença,%,Unnamed: 11,Unnamed: 12
0,1.0,NaN,SE Palmeiras,Série A,€ 227.88 mi.,36,€ 223.00 mi.,30,€ -4.88 mi.,-2.1 %,NaN,NaN,NaN
1,2.0,NaN,CR Flamengo,Série A,€ 222.95 mi.,31,€ 219.20 mi.,28,€ -3.75 mi.,-1.7 %,NaN,NaN,NaN
2,3.0,NaN,Cruzeiro EC,Série A,€ 81.50 mi.,38,€ 166.55 mi.,32,€ 85.05 mi.,104.4 %,NaN,NaN,NaN
3,4.0,NaN,SC Corinthians,Série A,€ 109.05 mi.,30,€ 154.30 mi.,34,€ 45.25 mi.,41.5 %,NaN,NaN,NaN
4,5.0,NaN,Botafogo FR,Série A,€ 161.80 mi.,39,€ 115.25 mi.,33,€ -46.55 mi.,-28.8 %,NaN,NaN,NaN
5,6.0,NaN,EC Bahia,Série A,€ 84.50 mi.,38,€ 114.35 mi.,32,€ 29.85 mi.,35.3 %,NaN,NaN,NaN
6,7.0,NaN,Fluminense FC,Série A,€ 77.05 mi.,36,€ 112.63 mi.,34,€ 35.58 mi.,46.2 %,NaN,NaN,NaN
7,8.0,NaN,Grêmio FBPA,Série A,€ 82.00 mi.,35,€ 103.85 mi.,33,€ 21.85 mi.,26.6 %,NaN,NaN,NaN
8,9.0,NaN,CR Vasco da Gama,Série A,€ 80.30 mi.,37,€ 101.20 mi.,28,€ 20.90 mi.,26.0 %,NaN,NaN,NaN
9,10.0,NaN,Santos FC,Série A,€ 54.65 mi.,43,€ 98.95 mi.,35,€ 44.30 mi.,81.1 %,NaN,NaN,NaN
10,11.0,NaN,RB Bragantino,Série A,€ 71.20 mi.,32,€ 89.00 mi.,35,€ 17.80 mi.,25.0 %,NaN,NaN,NaN
11,12.0,NaN,Atlético Mineiro,Série A,€ 86.70 mi.,31,€ 88.45 mi.,36,€ 1.75 mi.,2.0 %,NaN,NaN,NaN
12,13.0,NaN,São Paulo FC,Série A,€ 85.05 mi.,35,€ 84.55 mi.,40,€ -500 mil,-0.6 %,NaN,NaN,NaN
13,14.0,NaN,SC Internacional,Série A,€ 93.35 mi.,38,€ 71.60 mi.,30,€ -21.75 mi.,-23.3 %,NaN,NaN,NaN
14,15.0,NaN,Athletico Paranaense,NaN,€ 52.45 mi.,32,€ 44.48 mi.,29,€ -7.98 mi.,-15.2 %,NaN,NaN,NaN
15,16.0,NaN,EC Vitória,Série A,€ 25.38 mi.,37,€ 38.30 mi.,38,€ 12.93 mi.,50.9 %,NaN,NaN,NaN
16,17.0,NaN,Coritiba FC,NaN,€ 20.10 mi.,32,€ 36.00 mi.,30,€ 15.90 mi.,79.1 %,NaN,NaN,NaN
17,18.0,NaN,Clube do Remo,NaN,€ 3.73 mi.,22,€ 31.15 mi.,38,€ 27.43 mi.,736.2 %,NaN,NaN,NaN
18,19.0,NaN,Mirassol FC,Série A,€ 7.73 mi.,22,€ 29.00 mi.,32,€ 21.28 mi.,275.4 %,NaN,NaN,NaN
19,20.0,NaN,Chapecoense,NaN,€ 6.25 mi.,22,€ 17.65 mi.,39,€ 11.40 mi.,182.4 %,NaN,NaN,NaN
20,NaN,NaN,Valor total de todos os clubes,Valor total de todos os clubes,Valor total de todos os clubes,Valor total de todos os clubes,NaN,€ 1.63 Bi.,666,€ 1.94 Bi.,666.0,€ 305.85 mi.,18.7 %

,#,wappen,Clube,Clube.1,Pertence à liga01/01/2025,Valor01/01/2025,Jogadores no plantel 01/01/2025,Valor atual,Jogadores no plantel,Diferença,%,Unnamed: 11,Unnamed: 12
0,1.0,NaN,Fortaleza EC,Série A,€ 51.95 mi.,36,€ 34.40 mi.,29,€ -17.55 mi.,-33.8 %,NaN,NaN,NaN
1,2.0,NaN,Sport Recife,Série A,€ 13.85 mi.,25,€ 22.45 mi.,29,€ 8.60 mi.,62.1 %,NaN,NaN,NaN
2,3.0,NaN,Ceará SC,Série A,€ 15.00 mi.,31,€ 17.90 mi.,29,€ 2.90 mi.,19.3 %,NaN,NaN,NaN
3,4.0,NaN,Goiás EC,NaN,€ 14.30 mi.,38,€ 15.25 mi.,29,€ 950 mil,6.6 %,NaN,NaN,NaN
4,5.0,NaN,EC Juventude,Série A,€ 12.33 mi.,21,€ 13.20 mi.,29,€ 875 mil,7.1 %,NaN,NaN,NaN
5,6.0,NaN,Criciúma EC,NaN,€ 3.45 mi.,13,€ 12.23 mi.,35,€ 8.78 mi.,254.3 %,NaN,NaN,NaN
6,7.0,NaN,CRB,NaN,€ 7.10 mi.,25,€ 11.93 mi.,28,€ 4.83 mi.,68.0 %,NaN,NaN,NaN
7,8.0,NaN,Grêmio Novorizontino,Campeonato Paulista,€ 8.78 mi.,27,€ 10.50 mi.,36,€ 1.73 mi.,19.7 %,NaN,NaN,NaN
8,9.0,NaN,Cuiabá EC,NaN,€ 20.60 mi.,24,€ 10.48 mi.,38,€ -10.13 mi.,-49.2 %,NaN,NaN,NaN
9,10.0,NaN,Athletic Club,NaN,€ 2.50 mi.,31,€ 9.95 mi.,36,€ 7.45 mi.,298.0 %,NaN,NaN,NaN
10,11.0,NaN,América Mineiro,NaN,€ 12.70 mi.,24,€ 9.53 mi.,37,€ -3.18 mi.,-25.0 %,NaN,NaN,NaN
11,12.0,NaN,Atlético Goianiense,NaN,€ 12.50 mi.,27,€ 9.43 mi.,32,€ -3.08 mi.,-24.6 %,NaN,NaN,NaN
12,13.0,NaN,Operário FEC,NaN,€ 7.93 mi.,32,€ 8.80 mi.,35,€ 875 mil,11.0 %,NaN,NaN,NaN
13,14.0,NaN,Avaí FC,NaN,€ 10.40 mi.,30,€ 8.75 mi.,34,€ -1.65 mi.,-15.9 %,NaN,NaN,NaN
14,15.0,NaN,Vila Nova FC,NaN,€ 7.70 mi.,27,€ 7.68 mi.,28,€ -25 mil,-0.3 %,NaN,NaN,NaN
15,16.0,NaN,São Bernardo FC,Campeonato Paulista,€ 1.10 mi.,19,€ 7.53 mi.,33,€ 6.43 mi.,584.1 %,NaN,NaN,NaN
16,17.0,NaN,AA Ponte Preta,Campeonato Paulista,€ 5.00 mi.,25,€ 7.03 mi.,38,€ 2.03 mi.,40.5 %,NaN,NaN,NaN
17,18.0,NaN,Botafogo FC,Campeonato Paulista,€ 7.45 mi.,26,€ 5.18 mi.,34,€ -2.28 mi.,-30.5 %,NaN,NaN,NaN
18,19.0,NaN,Náutico,NaN,€ 425 mil,24,€ 4.38 mi.,33,€ 3.95 mi.,929.4 %,NaN,NaN,NaN
19,20.0,NaN,Londrina EC,NaN,€ 450 mil,12,€ 4.03 mi.,38,€ 3.58 mi.,794.4 %,NaN,NaN,NaN
20,NaN,NaN,Valor total de todos os clubes,Valor total de todos os clubes,Valor total de todos os clubes,Valor total de todos os clubes,NaN,€ 215.50 mi.,517,€ 230.58 mi.,660.0,€ 15.08 mi.,7.0 %

,#,wappen,Clube,Clube.1,Pertence à liga15/12/2025,Valor15/12/2025,Jogadores no plantel 15/12/2025,Valor atual,Jogadores no plantel,Diferença,%,Unnamed: 11,Unnamed: 12
0,1.0,NaN,SE Palmeiras,Série A,€ 232.30 mi.,29,€ 223.00 mi.,30,€ -9.30 mi.,-4.0 %,NaN,NaN,NaN
1,2.0,NaN,CR Flamengo,Série A,€ 187.50 mi.,32,€ 219.20 mi.,28,€ 31.70 mi.,16.9 %,NaN,NaN,NaN
2,3.0,NaN,Cruzeiro EC,Série A,€ 139.20 mi.,32,€ 166.55 mi.,32,€ 27.35 mi.,19.6 %,NaN,NaN,NaN
3,4.0,NaN,SC Corinthians,Série A,€ 114.50 mi.,32,€ 154.30 mi.,34,€ 39.80 mi.,34.8 %,NaN,NaN,NaN
4,5.0,NaN,Botafogo FR,Série A,€ 137.70 mi.,33,€ 115.25 mi.,33,€ -22.45 mi.,-16.3 %,NaN,NaN,NaN
5,6.0,NaN,EC Bahia,Série A,€ 114.05 mi.,30,€ 114.35 mi.,32,€ 300 mil,0.3 %,NaN,NaN,NaN
6,7.0,NaN,Fluminense FC,Série A,€ 94.83 mi.,34,€ 112.63 mi.,34,€ 17.80 mi.,18.8 %,NaN,NaN,NaN
7,8.0,NaN,Grêmio FBPA,Série A,€ 85.35 mi.,39,€ 103.85 mi.,33,€ 18.50 mi.,21.7 %,NaN,NaN,NaN
8,9.0,NaN,CR Vasco da Gama,Série A,€ 120.65 mi.,36,€ 101.20 mi.,28,€ -19.45 mi.,-16.1 %,NaN,NaN,NaN
9,10.0,NaN,Santos FC,Série A,€ 86.25 mi.,33,€ 98.95 mi.,35,€ 12.70 mi.,14.7 %,NaN,NaN,NaN
10,11.0,NaN,RB Bragantino,Série A,€ 89.90 mi.,37,€ 89.00 mi.,35,€ -900 mil,-1.0 %,NaN,NaN,NaN
11,12.0,NaN,Atlético Mineiro,Série A,€ 87.85 mi.,32,€ 88.45 mi.,36,€ 600 mil,0.7 %,NaN,NaN,NaN
12,13.0,NaN,São Paulo FC,Série A,€ 83.55 mi.,34,€ 84.55 mi.,40,€ 1.00 mi.,1.2 %,NaN,NaN,NaN
13,14.0,NaN,SC Internacional,Série A,€ 78.75 mi.,29,€ 71.60 mi.,30,€ -7.15 mi.,-9.1 %,NaN,NaN,NaN
14,15.0,NaN,Athletico Paranaense,Série B,€ 43.03 mi.,33,€ 44.48 mi.,29,€ 1.45 mi.,3.4 %,NaN,NaN,NaN
15,16.0,NaN,EC Vitória,Série A,€ 30.83 mi.,35,€ 38.30 mi.,38,€ 7.48 mi.,24.2 %,NaN,NaN,NaN
16,17.0,NaN,Coritiba FC,Série B,€ 21.35 mi.,32,€ 36.00 mi.,30,€ 14.65 mi.,68.6 %,NaN,NaN,NaN
17,18.0,NaN,Clube do Remo,Série B,€ 15.45 mi.,36,€ 31.15 mi.,38,€ 15.70 mi.,101.6 %,NaN,NaN,NaN
18,19.0,NaN,Mirassol FC,Série A,€ 27.00 mi.,33,€ 29.00 mi.,32,€ 2.00 mi.,7.4 %,NaN,NaN,NaN
19,20.0,NaN,Chapecoense,Série B,€ 10.65 mi.,34,€ 17.65 mi.,39,€ 7.00 mi.,65.7 %,NaN,NaN,NaN
20,NaN,NaN,Valor total de todos os clubes,Valor total de todos os clubes,Valor total de todos os clubes,Valor total de todos os clubes,NaN,€ 1.80 Bi.,665,€ 1.94 Bi.,666.0,€ 138.78 mi.,7.7 %

,#,wappen,Clube,Clube.1,Pertence à liga15/12/2025,Valor15/12/2025,Jogadores no plantel 15/12/2025,Valor atual,Jogadores no plantel,Diferença,%,Unnamed: 11,Unnamed: 12
0,1.0,NaN,Fortaleza EC,Série A,€ 43.80 mi.,37,€ 34.40 mi.,29,€ -9.40 mi.,-21.5 %,NaN,NaN,NaN
1,2.0,NaN,Sport Recife,Série A,€ 41.05 mi.,36,€ 22.45 mi.,29,€ -18.60 mi.,-45.3 %,NaN,NaN,NaN
2,3.0,NaN,Ceará SC,Série A,€ 31.58 mi.,32,€ 17.90 mi.,29,€ -13.68 mi.,-43.3 %,NaN,NaN,NaN
3,4.0,NaN,Goiás EC,Série B,€ 11.15 mi.,29,€ 15.25 mi.,29,€ 4.10 mi.,36.8 %,NaN,NaN,NaN
4,5.0,NaN,EC Juventude,Série A,€ 23.40 mi.,36,€ 13.20 mi.,29,€ -10.20 mi.,-43.6 %,NaN,NaN,NaN
5,6.0,NaN,Criciúma EC,Série B,€ 11.58 mi.,40,€ 12.23 mi.,35,€ 650 mil,5.6 %,NaN,NaN,NaN
6,7.0,NaN,CRB,Série B,€ 12.00 mi.,26,€ 11.93 mi.,28,€ -75 mil,-0.6 %,NaN,NaN,NaN
7,8.0,NaN,Grêmio Novorizontino,Série B,€ 12.53 mi.,30,€ 10.50 mi.,36,€ -2.03 mi.,-16.2 %,NaN,NaN,NaN
8,9.0,NaN,Cuiabá EC,Série B,€ 12.95 mi.,29,€ 10.48 mi.,38,€ -2.48 mi.,-19.1 %,NaN,NaN,NaN
9,10.0,NaN,Athletic Club,Série B,€ 8.43 mi.,35,€ 9.95 mi.,36,€ 1.53 mi.,18.1 %,NaN,NaN,NaN
10,11.0,NaN,América Mineiro,Série B,€ 13.55 mi.,37,€ 9.53 mi.,37,€ -4.03 mi.,-29.7 %,NaN,NaN,NaN
11,12.0,NaN,Atlético Goianiense,Série B,€ 14.28 mi.,33,€ 9.43 mi.,32,€ -4.85 mi.,-34.0 %,NaN,NaN,NaN
12,13.0,NaN,Operário FEC,Série B,€ 9.48 mi.,33,€ 8.80 mi.,35,€ -675 mil,-7.1 %,NaN,NaN,NaN
13,14.0,NaN,Avaí FC,Série B,€ 10.70 mi.,29,€ 8.75 mi.,34,€ -1.95 mi.,-18.2 %,NaN,NaN,NaN
14,15.0,NaN,Vila Nova FC,Série B,€ 7.53 mi.,32,€ 7.68 mi.,28,€ 150 mil,2.0 %,NaN,NaN,NaN
15,16.0,NaN,São Bernardo FC,Campeonato Paulista,€ 800 mil,28,€ 7.53 mi.,33,€ 6.73 mi.,840.6 %,NaN,NaN,NaN
16,17.0,NaN,AA Ponte Preta,Campeonato Paulista,€ 400 mil,27,€ 7.03 mi.,38,€ 6.63 mi.,1656.3 %,NaN,NaN,NaN
17,18.0,NaN,Botafogo FC,Série B,€ 6.05 mi.,33,€ 5.18 mi.,34,€ -875 mil,-14.5 %,NaN,NaN,NaN
18,19.0,NaN,Náutico,NaN,€ 1.00 mi.,32,€ 4.38 mi.,33,€ 3.38 mi.,337.5 %,NaN,NaN,NaN
19,20.0,NaN,Londrina EC,NaN,€ 50 mil,27,€ 4.03 mi.,38,€ 3.98 mi.,7950.0 %,NaN,NaN,NaN
20,NaN,NaN,Valor total de todos os clubes,Valor total de todos os clubes,Valor total de todos os clubes,Valor total de todos os clubes,NaN,€ 272.28 mi.,641,€ 230.58 mi.,660.0,€ -41.70 mi.,-15.3 %

     #  Clube        Clube.1  Unnamed: 3   V   E   D   Gols  SG  Pts
0    1    NaN       Flamengo          38  23  10   5  78:27  51   79
1    2    NaN      Palmeiras          38  23   7   8  66:33  33   76
2    3    NaN       Cruzeiro          38  19  13   6  55:31  24   70
3    4    NaN       Mirassol          38  18  13   7  63:39  24   67
4    5    NaN     Fluminense          38  19   7  12  50:39  11   64
5    6    NaN       Botafogo          38  17  12   9  58:38  20   63
6    7    NaN          Bahia          38  17   9  12  50:46   4   60
7    8    NaN      São Paulo          38  14   9  15  43:47  -4   51
8    9    NaN         Grêmio          38  13  10  15  47:50  -3   49
9   10    NaN     Bragantino          38  14   6  18  45:57 -12   48
10  11    NaN    Atlético-MG          38  12  12  14  43:44  -1   48
11  12    NaN         Santos          38  12  11  15  45:50  -5   47
12  13    NaN    Corinthians          38  12  11  15  42:47  -5   47
13  14    NaN  Vasco da Gama          38  13   6  19  55:60  -5   45
14  15    NaN        Vitória          38  11  12  15  35:52 -17   45
15  16    NaN  Internacional          38  11  11  16  44:57 -13   44
16  17    NaN          Ceará          38  11  10  17  34:40  -6   43
17  18    NaN      Fortaleza          38  11  10  17  43:58 -15   43
18  19    NaN      Juventude          38   9   8  21  35:69 -34   35
19  20    NaN          Sport          38   2  11  25  28:75 -47   17

,Club,Club.1,name,Squad,ø age,Foreigners,ø market value,Total market value
0,NaN,CR Flamengo,74.0,21.9,12,€3.70m,€273.50m,NaN
1,NaN,Sociedade Esportiva Palmeiras,54.0,22.9,11,€4.82m,€260.35m,NaN
2,NaN,Botafogo de Futebol e Regatas,82.0,23.2,17,€2.62m,€214.65m,NaN
3,NaN,Santos FC,52.0,24.6,12,€2.88m,€150.00m,NaN
4,NaN,Clube Atlético Mineiro,67.0,22.3,7,€1.91m,€127.75m,NaN
5,NaN,Grêmio Foot-Ball Porto Alegrense,58.0,23.9,13,€2.15m,€124.68m,NaN
6,NaN,Clube de Regatas Vasco da Gama,70.0,23.0,14,€1.75m,€122.60m,NaN
7,NaN,Cruzeiro Esporte Clube,50.0,23.2,10,€2.43m,€121.40m,NaN
8,NaN,Sport Club Corinthians Paulista,47.0,23.2,11,€2.24m,€105.40m,NaN
9,NaN,São Paulo Futebol Clube,55.0,23.8,12,€1.80m,€99.20m,NaN
10,NaN,Esporte Clube Bahia,72.0,22.1,6,€1.38m,€99.08m,NaN
11,NaN,Fluminense Football Club,71.0,23.3,12,€1.26m,€89.30m,NaN
12,NaN,Red Bull Bragantino,52.0,22.5,9,€1.66m,€86.53m,NaN
13,NaN,Sport Club Internacional,52.0,23.4,12,€1.60m,€83.25m,NaN
14,NaN,Fortaleza Esporte Clube,57.0,26.0,15,€1.09m,€61.95m,NaN
15,NaN,Sport Club do Recife,76.0,23.4,9,€696k,€52.91m,NaN
16,NaN,Esporte Clube Vitória,69.0,24.0,6,€627k,€43.28m,NaN
17,NaN,Ceará Sporting Club,48.0,25.7,5,€744k,€35.73m,NaN
18,NaN,Esporte Clube Juventude,57.0,25.3,5,€554k,€31.55m,NaN
19,NaN,Mirassol Futebol Clube (SP),50.0,27.2,0,€568k,€28.40m,NaN
20,NaN,NaN,NaN,1213.0,23.7 Years,198,€1.82m,€2.21bn

# Tratamento tabelas

Rename das colunas, remoção de valores nulos e valores desnecessários, adequação de colunas de str para numericos

In [56]:
def remove_null(df):
    df = df.iloc[:-1]
    df = df.drop(df.columns[0], axis=1)
    df = df.dropna(axis = 1, how = 'all')
    return df

def rename_colunas_inicio(df):
    df.columns = ['clube', 'liga', 'valor_01/01/2025', 'numero_jogadores_01/01/2025', 'valor_atual','numero_jogadores_atual', 'diferenca', '%']
    return df

def rename_colunas_fim(df):
    df.columns = ['clube', 'liga', 'valor_15/12/2025', 'numero_jogadores_15/12/2025', 'valor_atual','numero_jogadores_atual', 'diferenca', '%']
    return df

In [57]:
df_a_inicio = remove_null(df_a_inicio)
df_b_inicio = remove_null(df_b_inicio)
df_a_fim = remove_null(df_a_fim)
df_b_fim = remove_null(df_b_fim)
df_a_inicio = rename_colunas_inicio(df_a_inicio)
df_b_inicio = rename_colunas_inicio(df_b_inicio)
df_a_fim = rename_colunas_fim(df_a_fim)
df_b_fim = rename_colunas_fim(df_b_fim)
display( df_a_inicio, df_b_inicio, df_a_fim, df_b_fim)

,clube,liga,valor_01/01/2025,numero_jogadores_01/01/2025,valor_atual,numero_jogadores_atual,diferenca,%
0,SE Palmeiras,Série A,€ 227.88 mi.,36,€ 223.00 mi.,30,€ -4.88 mi.,-2.1 %
1,CR Flamengo,Série A,€ 222.95 mi.,31,€ 219.20 mi.,28,€ -3.75 mi.,-1.7 %
2,Cruzeiro EC,Série A,€ 81.50 mi.,38,€ 166.55 mi.,32,€ 85.05 mi.,104.4 %
3,SC Corinthians,Série A,€ 109.05 mi.,30,€ 154.30 mi.,34,€ 45.25 mi.,41.5 %
4,Botafogo FR,Série A,€ 161.80 mi.,39,€ 115.25 mi.,33,€ -46.55 mi.,-28.8 %
5,EC Bahia,Série A,€ 84.50 mi.,38,€ 114.35 mi.,32,€ 29.85 mi.,35.3 %
6,Fluminense FC,Série A,€ 77.05 mi.,36,€ 112.63 mi.,34,€ 35.58 mi.,46.2 %
7,Grêmio FBPA,Série A,€ 82.00 mi.,35,€ 103.85 mi.,33,€ 21.85 mi.,26.6 %
8,CR Vasco da Gama,Série A,€ 80.30 mi.,37,€ 101.20 mi.,28,€ 20.90 mi.,26.0 %
9,Santos FC,Série A,€ 54.65 mi.,43,€ 98.95 mi.,35,€ 44.30 mi.,81.1 %
10,RB Bragantino,Série A,€ 71.20 mi.,32,€ 89.00 mi.,35,€ 17.80 mi.,25.0 %
11,Atlético Mineiro,Série A,€ 86.70 mi.,31,€ 88.45 mi.,36,€ 1.75 mi.,2.0 %
12,São Paulo FC,Série A,€ 85.05 mi.,35,€ 84.55 mi.,40,€ -500 mil,-0.6 %
13,SC Internacional,Série A,€ 93.35 mi.,38,€ 71.60 mi.,30,€ -21.75 mi.,-23.3 %
14,Athletico Paranaense,NaN,€ 52.45 mi.,32,€ 44.48 mi.,29,€ -7.98 mi.,-15.2 %
15,EC Vitória,Série A,€ 25.38 mi.,37,€ 38.30 mi.,38,€ 12.93 mi.,50.9 %
16,Coritiba FC,NaN,€ 20.10 mi.,32,€ 36.00 mi.,30,€ 15.90 mi.,79.1 %
17,Clube do Remo,NaN,€ 3.73 mi.,22,€ 31.15 mi.,38,€ 27.43 mi.,736.2 %
18,Mirassol FC,Série A,€ 7.73 mi.,22,€ 29.00 mi.,32,€ 21.28 mi.,275.4 %
19,Chapecoense,NaN,€ 6.25 mi.,22,€ 17.65 mi.,39,€ 11.40 mi.,182.4 %

,clube,liga,valor_01/01/2025,numero_jogadores_01/01/2025,valor_atual,numero_jogadores_atual,diferenca,%
0,Fortaleza EC,Série A,€ 51.95 mi.,36,€ 34.40 mi.,29,€ -17.55 mi.,-33.8 %
1,Sport Recife,Série A,€ 13.85 mi.,25,€ 22.45 mi.,29,€ 8.60 mi.,62.1 %
2,Ceará SC,Série A,€ 15.00 mi.,31,€ 17.90 mi.,29,€ 2.90 mi.,19.3 %
3,Goiás EC,NaN,€ 14.30 mi.,38,€ 15.25 mi.,29,€ 950 mil,6.6 %
4,EC Juventude,Série A,€ 12.33 mi.,21,€ 13.20 mi.,29,€ 875 mil,7.1 %
5,Criciúma EC,NaN,€ 3.45 mi.,13,€ 12.23 mi.,35,€ 8.78 mi.,254.3 %
6,CRB,NaN,€ 7.10 mi.,25,€ 11.93 mi.,28,€ 4.83 mi.,68.0 %
7,Grêmio Novorizontino,Campeonato Paulista,€ 8.78 mi.,27,€ 10.50 mi.,36,€ 1.73 mi.,19.7 %
8,Cuiabá EC,NaN,€ 20.60 mi.,24,€ 10.48 mi.,38,€ -10.13 mi.,-49.2 %
9,Athletic Club,NaN,€ 2.50 mi.,31,€ 9.95 mi.,36,€ 7.45 mi.,298.0 %
10,América Mineiro,NaN,€ 12.70 mi.,24,€ 9.53 mi.,37,€ -3.18 mi.,-25.0 %
11,Atlético Goianiense,NaN,€ 12.50 mi.,27,€ 9.43 mi.,32,€ -3.08 mi.,-24.6 %
12,Operário FEC,NaN,€ 7.93 mi.,32,€ 8.80 mi.,35,€ 875 mil,11.0 %
13,Avaí FC,NaN,€ 10.40 mi.,30,€ 8.75 mi.,34,€ -1.65 mi.,-15.9 %
14,Vila Nova FC,NaN,€ 7.70 mi.,27,€ 7.68 mi.,28,€ -25 mil,-0.3 %
15,São Bernardo FC,Campeonato Paulista,€ 1.10 mi.,19,€ 7.53 mi.,33,€ 6.43 mi.,584.1 %
16,AA Ponte Preta,Campeonato Paulista,€ 5.00 mi.,25,€ 7.03 mi.,38,€ 2.03 mi.,40.5 %
17,Botafogo FC,Campeonato Paulista,€ 7.45 mi.,26,€ 5.18 mi.,34,€ -2.28 mi.,-30.5 %
18,Náutico,NaN,€ 425 mil,24,€ 4.38 mi.,33,€ 3.95 mi.,929.4 %
19,Londrina EC,NaN,€ 450 mil,12,€ 4.03 mi.,38,€ 3.58 mi.,794.4 %

,clube,liga,valor_15/12/2025,numero_jogadores_15/12/2025,valor_atual,numero_jogadores_atual,diferenca,%
0,SE Palmeiras,Série A,€ 232.30 mi.,29,€ 223.00 mi.,30,€ -9.30 mi.,-4.0 %
1,CR Flamengo,Série A,€ 187.50 mi.,32,€ 219.20 mi.,28,€ 31.70 mi.,16.9 %
2,Cruzeiro EC,Série A,€ 139.20 mi.,32,€ 166.55 mi.,32,€ 27.35 mi.,19.6 %
3,SC Corinthians,Série A,€ 114.50 mi.,32,€ 154.30 mi.,34,€ 39.80 mi.,34.8 %
4,Botafogo FR,Série A,€ 137.70 mi.,33,€ 115.25 mi.,33,€ -22.45 mi.,-16.3 %
5,EC Bahia,Série A,€ 114.05 mi.,30,€ 114.35 mi.,32,€ 300 mil,0.3 %
6,Fluminense FC,Série A,€ 94.83 mi.,34,€ 112.63 mi.,34,€ 17.80 mi.,18.8 %
7,Grêmio FBPA,Série A,€ 85.35 mi.,39,€ 103.85 mi.,33,€ 18.50 mi.,21.7 %
8,CR Vasco da Gama,Série A,€ 120.65 mi.,36,€ 101.20 mi.,28,€ -19.45 mi.,-16.1 %
9,Santos FC,Série A,€ 86.25 mi.,33,€ 98.95 mi.,35,€ 12.70 mi.,14.7 %
10,RB Bragantino,Série A,€ 89.90 mi.,37,€ 89.00 mi.,35,€ -900 mil,-1.0 %
11,Atlético Mineiro,Série A,€ 87.85 mi.,32,€ 88.45 mi.,36,€ 600 mil,0.7 %
12,São Paulo FC,Série A,€ 83.55 mi.,34,€ 84.55 mi.,40,€ 1.00 mi.,1.2 %
13,SC Internacional,Série A,€ 78.75 mi.,29,€ 71.60 mi.,30,€ -7.15 mi.,-9.1 %
14,Athletico Paranaense,Série B,€ 43.03 mi.,33,€ 44.48 mi.,29,€ 1.45 mi.,3.4 %
15,EC Vitória,Série A,€ 30.83 mi.,35,€ 38.30 mi.,38,€ 7.48 mi.,24.2 %
16,Coritiba FC,Série B,€ 21.35 mi.,32,€ 36.00 mi.,30,€ 14.65 mi.,68.6 %
17,Clube do Remo,Série B,€ 15.45 mi.,36,€ 31.15 mi.,38,€ 15.70 mi.,101.6 %
18,Mirassol FC,Série A,€ 27.00 mi.,33,€ 29.00 mi.,32,€ 2.00 mi.,7.4 %
19,Chapecoense,Série B,€ 10.65 mi.,34,€ 17.65 mi.,39,€ 7.00 mi.,65.7 %

,clube,liga,valor_15/12/2025,numero_jogadores_15/12/2025,valor_atual,numero_jogadores_atual,diferenca,%
0,Fortaleza EC,Série A,€ 43.80 mi.,37,€ 34.40 mi.,29,€ -9.40 mi.,-21.5 %
1,Sport Recife,Série A,€ 41.05 mi.,36,€ 22.45 mi.,29,€ -18.60 mi.,-45.3 %
2,Ceará SC,Série A,€ 31.58 mi.,32,€ 17.90 mi.,29,€ -13.68 mi.,-43.3 %
3,Goiás EC,Série B,€ 11.15 mi.,29,€ 15.25 mi.,29,€ 4.10 mi.,36.8 %
4,EC Juventude,Série A,€ 23.40 mi.,36,€ 13.20 mi.,29,€ -10.20 mi.,-43.6 %
5,Criciúma EC,Série B,€ 11.58 mi.,40,€ 12.23 mi.,35,€ 650 mil,5.6 %
6,CRB,Série B,€ 12.00 mi.,26,€ 11.93 mi.,28,€ -75 mil,-0.6 %
7,Grêmio Novorizontino,Série B,€ 12.53 mi.,30,€ 10.50 mi.,36,€ -2.03 mi.,-16.2 %
8,Cuiabá EC,Série B,€ 12.95 mi.,29,€ 10.48 mi.,38,€ -2.48 mi.,-19.1 %
9,Athletic Club,Série B,€ 8.43 mi.,35,€ 9.95 mi.,36,€ 1.53 mi.,18.1 %
10,América Mineiro,Série B,€ 13.55 mi.,37,€ 9.53 mi.,37,€ -4.03 mi.,-29.7 %
11,Atlético Goianiense,Série B,€ 14.28 mi.,33,€ 9.43 mi.,32,€ -4.85 mi.,-34.0 %
12,Operário FEC,Série B,€ 9.48 mi.,33,€ 8.80 mi.,35,€ -675 mil,-7.1 %
13,Avaí FC,Série B,€ 10.70 mi.,29,€ 8.75 mi.,34,€ -1.95 mi.,-18.2 %
14,Vila Nova FC,Série B,€ 7.53 mi.,32,€ 7.68 mi.,28,€ 150 mil,2.0 %
15,São Bernardo FC,Campeonato Paulista,€ 800 mil,28,€ 7.53 mi.,33,€ 6.73 mi.,840.6 %
16,AA Ponte Preta,Campeonato Paulista,€ 400 mil,27,€ 7.03 mi.,38,€ 6.63 mi.,1656.3 %
17,Botafogo FC,Série B,€ 6.05 mi.,33,€ 5.18 mi.,34,€ -875 mil,-14.5 %
18,Náutico,NaN,€ 1.00 mi.,32,€ 4.38 mi.,33,€ 3.38 mi.,337.5 %
19,Londrina EC,NaN,€ 50 mil,27,€ 4.03 mi.,38,€ 3.98 mi.,7950.0 %

In [58]:
df_geral_1 = df_geral.iloc[:-1]
df_geral_2 = df_geral_1.dropna(axis= 1, how = 'all')
df_geral_2.columns = ['clube', 'numero_jogadores', 'media_idade', 'estrangeiros', 'media_valor_mercado_', 'valor_mercado_total']
df_geral_2

,clube,numero_jogadores,media_idade,estrangeiros,media_valor_mercado_,valor_mercado_total
0,CR Flamengo,74.0,21.9,12,€3.70m,€273.50m
1,Sociedade Esportiva Palmeiras,54.0,22.9,11,€4.82m,€260.35m
2,Botafogo de Futebol e Regatas,82.0,23.2,17,€2.62m,€214.65m
3,Santos FC,52.0,24.6,12,€2.88m,€150.00m
4,Clube Atlético Mineiro,67.0,22.3,7,€1.91m,€127.75m
5,Grêmio Foot-Ball Porto Alegrense,58.0,23.9,13,€2.15m,€124.68m
6,Clube de Regatas Vasco da Gama,70.0,23.0,14,€1.75m,€122.60m
7,Cruzeiro Esporte Clube,50.0,23.2,10,€2.43m,€121.40m
8,Sport Club Corinthians Paulista,47.0,23.2,11,€2.24m,€105.40m
9,São Paulo Futebol Clube,55.0,23.8,12,€1.80m,€99.20m
10,Esporte Clube Bahia,72.0,22.1,6,€1.38m,€99.08m
11,Fluminense Football Club,71.0,23.3,12,€1.26m,€89.30m
12,Red Bull Bragantino,52.0,22.5,9,€1.66m,€86.53m
13,Sport Club Internacional,52.0,23.4,12,€1.60m,€83.25m
14,Fortaleza Esporte Clube,57.0,26.0,15,€1.09m,€61.95m
15,Sport Club do Recife,76.0,23.4,9,€696k,€52.91m
16,Esporte Clube Vitória,69.0,24.0,6,€627k,€43.28m
17,Ceará Sporting Club,48.0,25.7,5,€744k,€35.73m
18,Esporte Clube Juventude,57.0,25.3,5,€554k,€31.55m
19,Mirassol Futebol Clube (SP),50.0,27.2,0,€568k,€28.40m

In [59]:
df_class_1 = df_class.dropna(axis= 1, how = 'all')
df_class_2 = df_class_1.drop(df_class_1.columns[[0, 2]], axis=1)
df_class_2.columns = ['clube', 'v', 'e', 'd', 'gols', 'sg', 'pontos']

In [60]:
def normalizador_numericos(df):
    for coluna in df:
        if df[coluna].dtype == 'str' or df[coluna].dtype == 'object':
            mask_tem_numero = df[coluna].str.contains(r'\d', na=False)
            
            if mask_tem_numero.any():
                milhar = df[coluna].str.contains(r'k|mil', case=False, na=False)
                
                df[coluna] = df[coluna].str.replace(r'\.$', '', regex=True)
                
                df[coluna] = df[coluna].str.replace(r'[^\d.-]', '', regex=True)
                
                valores_numericos = pd.to_numeric(df[coluna], errors='coerce')
                
                df[coluna] = np.where(
                    milhar,
                    valores_numericos / 1000, 
                    valores_numericos
                )
            
    return df

In [61]:
lista_df = [df_a_inicio,df_b_inicio,df_a_fim,df_b_fim, df_geral_2]
for df in lista_df:
    normalizador_numericos(df)

In [ ]:
lista_df_db = {'df_a_inicio' : df_a_inicio,
               'df_b_inicio' : df_b_inicio,
               'df_a_fim' : df_a_fim,
               'df_b_fim' : df_b_fim,
               'df_geral' : df_geral_2,
               'df_class' : df_class_2}

In [ ]:
def salvar_db(dfs):
    conn = sqlite3.connect('/workspaces/moneyball-brasileirao/databases/brasileirao.db')
    
    for nome_tabela, df in dfs.items():  
        df.to_sql(name=nome_tabela, con=conn, if_exists='replace', index=False)    
    conn.close()

salvar_db(lista_df_db)

Tabela 'df_a_inicio' processada e salva.
Tabela 'df_b_inicio' processada e salva.
Tabela 'df_a_fim' processada e salva.
Tabela 'df_b_fim' processada e salva.
Tabela 'df_geral_2' processada e salva.
Tabela 'df_class_2' processada e salva.

🚀 Todos os bancos foram atualizados com sucesso!